services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    container_name: mlflow-server
    ports:
      - "5001:5001"
    command: mlflow server --host 0.0.0.0 --port 5001
  model:
    build: .
    container_name: pixel-rest
    ports:
      - "9001:9001"
