model:
  upscale_factor: 4 # super resolution upscale factor

  generator:
    out_channels: 64
    block1:
      kernel_size: 9
      padding: 4
    block7:
      kernel_size: 3
      padding: 1
    block8:
      kernel_size: 9
      padding: 4
    upsample_block:
      kernel_size: 3
      padding: 1

  discriminator:
    out_channels: 64
    kernel_size: 3
    padding: 1
    leaky_coef: 0.2

  loss:
    generator:
      adversarial_weight: 0.001
      perception_weight: 0.006
      tv_weight: 2.e-8

train:
  data_path: data/train
  crop_size: 88 # training images crop size
  num_epochs: 1 # train epoch number
  num_workers: 4
  batch_size: 64
  shuffle: True

val:
  data_path: data/val
  num_workers: 4
  batch_size: 1
  shuffle: False
  chunk_size: 1

infer:
  data_path: data/inf
  num_workers: 4
  batch_size: 1
  shuffle: False
  chunk_size: 15
